version: "3"
services:
  db:
    # TODO: configura tu imagen de base de datos, te recomendamos una de las sgtes:
    # https://hub.docker.com/_/mysql
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: rootroot
        MYSQL_DATABASE: bq
        MYSQL_USER: user
        MYSQL_PASSWORD: lim012
    volumes:
      - mysql_data:/var/lib/mysql  
    ports:
      - "5000:3306"
      - "5001:33060"
    networks:
      - public
      - private
  node:
    image: "node:14" # https://hub.docker.com/_/node/
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - DHOST=db
      - DUSER_DB=root
      - DPASSWORD_DB=rootroot
      - DDB_NAME=bq
      - Port=8080
    links: 
      - db
    env_file:
      - secrets.env # los _secrets_ a incluir como variables de entorno. Usa el archivo `sample.secrets.env` como guia
    volumes:
      - ./:/home/node/app # montamos el codigo en el HOME del usuario _node_
    expose:
    - "8000" # nuestra app corre en el puerto 8080
    ports:
      - "80:8000" # mapeamos el puerto 8080 de nuestro contenedor al puerto 80 de nuestra maquina
    command: "bash -c 'rm -rf node_modules && npm install && npm start'" # reinstalamos las dependencias y levantamos el servidor
    depends_on:
      - db
    networks:
      - public
      - private
volumes:
  mysql_data:     
networks:
  public:
    internal: false
  private:
    internal: true
